"""Add km_rate and daily_allowance_rate to projects

Revision ID: 8a5d35a5d72c
Revises: 004
Create Date: 2026-04-09 13:26:13.230494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5d35a5d72c'
down_revision: Union[str, Sequence[str], None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('km_rate', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('projects', sa.Column('daily_allowance_rate', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'daily_allowance_rate')
    op.drop_column('projects', 'km_rate')
    # ### end Alembic commands ###
