"""add soft delete fields

Revision ID: dc111475b166
Revises: 003_project_travel_times
Create Date: 2026-03-20 19:57:26.198518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc111475b166'
down_revision: Union[str, Sequence[str], None] = '003_project_travel_times'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'requires_extra_fields',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'allowed_roles',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using="array_to_json(allowed_roles)")
    op.add_column('time_entries', sa.Column('trip_type', sa.String(length=10), nullable=True))
    op.add_column('time_entries', sa.Column('travel_time', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('time_entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('time_entries', 'deleted_at')
    op.drop_column('time_entries', 'travel_time')
    op.drop_column('time_entries', 'trip_type')
    op.alter_column('tasks', 'allowed_roles',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=False,
               postgresql_using="ARRAY(SELECT json_array_elements_text(allowed_roles))")
    op.alter_column('tasks', 'requires_extra_fields',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('projects', 'deleted_at')
    # ### end Alembic commands ###
